dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
notifications:
  email: false
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install -U importlib_metadata
  - pip install coveralls
# note that pip install -U importlib_metadata is to fix an issue with python 3.7 only.
#  see: https://travis-ci.community/t/build-error-for-python-3-7-on-two-different-projects/12895/2
# commands to run tests, generate coverage report, and pipe the report to coveralls:
# see https://levibostian.com/blog/python-code-coverage-and-coveralls-io/
script:
  - pytest --cov=htof/
after_success:
  - coveralls
